"""empty message

Revision ID: 36491dd0649d
Revises: 46fb46f25382
Create Date: 2020-07-14 11:14:45.451390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36491dd0649d'
down_revision = '46fb46f25382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuadraturas_cajas', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.drop_constraint('cuadraturas_cajas_ibfk_1', 'cuadraturas_cajas', type_='foreignkey')
    op.create_foreign_key(None, 'cuadraturas_cajas', 'usuarios', ['admin_id'], ['id'])
    op.drop_column('cuadraturas_cajas', 'administrador')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuadraturas_cajas', sa.Column('administrador', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cuadraturas_cajas', type_='foreignkey')
    op.create_foreign_key('cuadraturas_cajas_ibfk_1', 'cuadraturas_cajas', 'usuarios', ['administrador'], ['id'])
    op.drop_column('cuadraturas_cajas', 'admin_id')
    # ### end Alembic commands ###
