"""empty message

Revision ID: 46fb46f25382
Revises: 
Create Date: 2020-07-13 18:04:37.552433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fb46f25382'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('documentos_ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('numero_documento', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('monto_neto', sa.Float(), nullable=False),
    sa.Column('monto_iva', sa.Float(), nullable=False),
    sa.Column('monto_otros_impuestos', sa.Float(), nullable=False),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('forma_pago', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rut', sa.String(length=13), nullable=False),
    sa.Column('razon_social', sa.String(length=100), nullable=False),
    sa.Column('rubro', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razon_social'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rut', sa.String(length=13), nullable=False),
    sa.Column('razon_social', sa.String(length=100), nullable=False),
    sa.Column('rubro', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=False),
    sa.Column('cuenta_corriente', sa.String(length=100), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razon_social'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('facturas_compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('fecha_recepcion', sa.DateTime(), nullable=False),
    sa.Column('monto_neto', sa.Float(), nullable=False),
    sa.Column('monto_iva', sa.Float(), nullable=False),
    sa.Column('monto_otros_impuestos', sa.Float(), nullable=False),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('codigo_barra', sa.String(length=100), nullable=False),
    sa.Column('unidad_entrega', sa.String(length=100), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('precio_venta_unitario', sa.Float(), nullable=True),
    sa.Column('margen_contribucion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barra'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('cuadraturas_cajas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('administrador', sa.Integer(), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=False),
    sa.Column('monto_apertura', sa.Float(), nullable=False),
    sa.Column('monto_transferencia', sa.Float(), nullable=False),
    sa.Column('monto_efectivo', sa.Float(), nullable=False),
    sa.Column('monto_tarjeta', sa.Float(), nullable=False),
    sa.Column('monto_cierre', sa.Float(), nullable=False),
    sa.Column('diferencia_en_caja', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['administrador'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entradas_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_costo_unitario', sa.Float(), nullable=False),
    sa.Column('costo_total', sa.Float(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('factura_compra_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['factura_compra_id'], ['facturas_compras.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salidas_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_costo_unitario', sa.Float(), nullable=False),
    sa.Column('costo_total', sa.Float(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('documento_venta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['documento_venta_id'], ['documentos_ventas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salidas_inventario')
    op.drop_table('entradas_inventario')
    op.drop_table('cuadraturas_cajas')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('facturas_compras')
    op.drop_table('proveedores')
    op.drop_table('empresas')
    op.drop_table('documentos_ventas')
    op.drop_table('categorias')
    # ### end Alembic commands ###
